name: Deploy Static Site to EC2

on:
push:
branches:
- main   # change if your repo uses master

jobs:
deploy:
runs-on: ubuntu-latest


steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Deploy to EC2 via SSH
    uses: appleboy/ssh-action@master
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: ${{ secrets.EC2_KEY }}
      script: |
        cd /var/www/Priyafreshmeats
        git fetch origin main
        git reset --hard origin/main
        sudo systemctl reload nginx
